name: Bedwars-001
version: 1.0.0
main: com.Thunderlight11jk.bedwars.BedWarsPlugin
api-version: 1.8.8
softdepend: [Vault]
author: Thunderlight11jk
description: Bedwars Plugin!

commands:
  bw:
    description: Main BedWars command
    usage: /bw <help|setup|join|leave|setlobby|create|delete|list>
    aliases: [bedwars]
  bwadmin:
    description: BedWars admin commands
    usage: /bwadmin <reload|forcestart|forcestop>
    permission: bedwars.admin
  leave:
    description: Leave the current game
    usage: /leave
